module.exports = {
  SUCCESS: "You did a successful operation",
  FAILURE: "Your operation failed",
  LOGOUT:  "Your Logout Successfully",
  USER_FOUND:"User found successfully",
  USER_NOT_FOUND:"User Not Found",
  INVALID_CRED:"Ivvalid Credincials",
  LOGIN_SUCCESS:"User Login Successfully",
  USER_DETAILS:"User Details Fetch Successfully",
  AUTH_ERROR:"Auth Error",
  EMAIL_EXIS:"Email Already Exists",
  NOT_ADDED:"Something Went Wrong User Not Added",
  USER_ADDED:"User Added Successfully",
  USER_NOT_UPDATE:"User Already Updated",
  USER_UPDATE:"User Update Successfully",
  USER_NOT_DELETE:"User Already Deleted",
  USER_DELETE:"User Delete Successfully",
  NOT_EXIS:"User Not Exists",
  PASS_EXIST:"Please Try with Different Password",
  PASS_CHANGED:"Password changed now you can login with the updated password",
  PASS_NOT_CHANGED:"Password not changed",
  NO_RIGTHS:"You Do Have Not Enough Rights",
  BLOG_CREATED:"Blog created successfully",
  BLOIG_NOT_CREATED:"Error while creating blog",
  BLOG_FETCHED:"BLog fetched Successfully",
  PROFILE_NOT_CREATED:"Error while creating profile",
  BLOG_NOT_FOUND:"No blogs found for this id",
  PUBLISH_ERROR:"Error while publishing blog",
  BLOG_PUBLISH:"Blog published successfully",
  TOPIC_CREATE_ERROR:"Error While Creating Topic",
  TOPIC_CREATED:"Topic created successfully",
  TOPIC_FETCH:"Topic fetch successfully",
  ERROR_TOPIC_FETCH:"Error while fetching topic",
  TOPIC_DELETE:"Topic delete successfully",
  ERROR_TOPIC_DELETE:"Error while delete topic",
  ERROR_TOPIC_UPDATE:"Error while update topic",
  TOPIC_UPDATE:"Topic update successfully",
  TOPIC_NOT_PRESENT:"Topic not present for this id"
}